# Generated by Django 3.1.7 on 2021-03-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0004_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team')),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='events'),
        ),
    ]
